# -*- coding: utf-8 -*-
"""NumpyPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHXMFWTwJFvGz15o0fsiEWkNCEnfApjm

#The Numpy Library

Here I present a lot of basic functions and things you can do with the numpy module, seeing that it's one of the most important modules for use in the matplotlib and pandas and keras library
"""

import numpy as np

a = np.array([1,2,4])
b = np.array([[1,2,4,5],[3,4,1,2]],dtype='int16')
c = np.array([2,3,4])

"""##Splicing """

print(a[1:3])
print(a[:])

print(b[1:,]) #grabbing the 2nd row
print(b[:,1]) #all rows, column 2
print(b[:,:]) #the whole matrix

print(b[:,1:3]) #all rows, the first index up till second index elements
#when you use the a:b notation for splicing, we exclude the b'th index

"""##Operations

Those including sum, difference, multiplication and exponentiation
"""

print(a+c)
print(a*c)
print(a-c)
print(a**2)

"""##Matrix Multiplication

We can also do matrix multiplication but remember that we have two matrices A and B and we want to get their matrix product the dimensions must be similar in the following manner:

A = p x n     
B = n x m    
C = A x B -> p x m Dimensions
"""

d = np.array([[2,2],[3,3]])
e = np.array([[1,2],[3,1]])

print(np.matmul(d,e))

"""##Determinant"""

print(np.linalg.det(e))

"""##Statistics

###Min
"""

print(np.min(e)) #minimum of the elements of the whole array

print(np.amin(e,axis=0)) #minimum of the elements in the first column
#it will return the

"""###Max """

print(np.max(e)) #max of the whole array
print(np.amax(e,axis=1)) #max element of the first row in the matrix

"""###Sum"""

h = np.array([1,4,5,9])
print(np.sum(h))
print(np.cumsum(h))

"""###Cumulative Sum"""

print(np.cumsum(h)) #this will return an array with the sum accumulating
print(np.sum(e,axis=1)) #also returns in an array

"""###Normal Distribution

We can work with a normal distribution and get a handful of numbers that follow the normal curve with the:

np.random.normal(loc = mean, scale = st.dev, size = (nxm)
"""

a1 = np.random.normal(2,size=(1,6))
a1

"""##File I/O"""

try:
  filedata = np.genfromtxt('data.txt',delimiter=',')  #so this function will return an array
  filedata = filedata.astype('int32') #astype will return the new array but doesn't change
  #the actual array
except Exception:
  print("Random Exception")

"""##Masking

###Boolean Mask
"""

print(h > 2) #we return the same array but with boolean values
#according to the expression given inside

#Now we want to find the columns that are > 2
e = np.array([[1,2,3,4,5,6,7,8],[3,1,7,4,3,2,1,9]])

#use the np.any or np.all to evaluate all or any of the elements in a column or row
#meet the criteria

"""###Any"""

print(np.any(e > 3,axis=0)) #we will look at all the columns and see if any of the
#row elements are > 3
print(np.any(e > 3,axis=1)) #we will look at all the rows and see if any of the
#column elements are > 3 -> we have two rows only

"""###All"""

print(np.all(e > 3,axis=0)) #we will look at all the columns and see if any of the
#row elements are > 3
print(np.all(e > 3,axis=1)) #we will look at all the rows and see if any of the
#column elements are > 3 -> we have two rows only

"""##Weird Indexing"""

a1 = np.array([1,2,3,4,5,6,7,8,9,10])
#Now we want to return an array containing the elements at 
#index 0,4,7,8
print(a1[[0,4,7,8]])
#This is called LIST INDEXING

e = np.array([[1,2,3,4,5,6,7,8],[3,1,7,4,3,2,1,9]])
print(e[[1],[4,5,6,7]])

# we want the elements in the first row and then the 4-6th index

"""##Stacking

###Horizontal Stacking

Arrays are stacked horizontally, columnwise
"""

a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.hstack((a,b)))

"""###Vertical Stacking

Arrays are stacked vertically, row wise so we increase the dimension
"""

a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.vstack((a,b)))

"""##Random Module

###Random Array
"""

print(np.random.randint(4,15,size=(2,3))) 
#Make an array 3x2 which has random elements btw 4 and 15(exclusive)

"""###Random Shuffling

np.random.shuffle(a numpy arr)

Returns:
  None
"""

a = np.random.randint(1,4,size=5)
np.random.shuffle(a)
a

"""#Numpy Exercises

1. *Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.*
"""

import numpy as np

print(np.zeros((5,6))) #the 5x6 is given as a tuple for input

"""2. *Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number*"""

def arrTester(array,function):
  '''
  Here we return a boolean array of the 
  same shape
  '''
  return function(array)

def arrExtraction(array,function):
  '''
  Here we return the elements that are true
  because the function(array) will return an 
  array of boolean values and indexing with boolean values
  means we work with the true values 
  '''
  return array[function(array)] 

array = np.array([1,2,3,4,5,6,7])

print(arrTester(array,lambda x: x > 3))
print(arrTester(array,lambda x: x < 5))

print(arrExtraction(array,lambda x: x < 5))

"""3. *Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.* """

def arrConverter(array,function,convert):
  '''
  Here we return the new array with all elements
  that meet the boolean condition in "function"
  converted to a number in the parameters
  return:
    New array with conversion
  parameters:
    array - a numpy array
    function - lambda function with boolean expression
    convert - number to convert all nums meeting condition to
  '''
  array[function(array)] = 100
  return array

print(arrConverter(array,lambda x: x < 5,100))

"""4. *Write a NumPy program to multiply two given arrays of same size element-by-element.*"""

a = np.array([1,4,7,8])
b = 2 * a.copy()
print(a*b)
print(a**b)
print(a/b)
print(a+b)

"""As you can see we can perform all sorts of operations with two arrays but the operation is done element-wise

5. *Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.*

So in this problem we can make that array and set it to a specific number
"""

print(np.full((3,4,5),fill_value=2,dtype='int8'))

print(np.full((4,5),fill_value=7,dtype='int8'))

"""6. *Write a NumPy program to create an array of equal shape and data type of a given array.*"""

#easy seems like a copy
a = np.array([1,3,4,5,6])
print(a.copy())

#or just an empty array of the same type - maybe filled with 0s
print(np.zeros_like(a))

"""7. *Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1.*"""

print(np.random.randint(4,11,size=5)) #exclude the 11
#Now we made an array of size = 5 with 5 random elements